import Link from "./Link";
import PropTypes from "prop-types";
import "./DestinationGrid.css";

const DestinationGrid = ({ className = "" }) => {
  return (
    <div className={`destination-grid ${className}`}>
      <Link
        border="/border@2x.png"
        turkey="Afghanistan"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Albania"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Algeria"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Andorra"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Anguilla"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Argentina"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Armenia"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Aruba"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Australia"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Austria"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Azerbaijan"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Bahrain"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Bangladesh"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Barbados"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Belgium"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Benin"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Bermuda"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Bolivia"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Botswana"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Brazil"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Bulgaria"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Cambodia"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Cameroon"
        img="/img1@2x.png"
        propGap="20px"
      />
      <div className="link1">
        <div className="border-parent">
          <div className="border">
            <img className="image-icon2" alt="" src="/image@2x.png" />
          </div>
          <div className="canada">Canada</div>
        </div>
        <img className="img-icon3" alt="" src="/img1@2x.png" />
      </div>
      <Link
        border="/border@2x.png"
        turkey="Chad"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Chile"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="China"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Colombia"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Costa Rica"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Croatia"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Cyprus"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Czech Republic"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Denmark"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Dominica"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Dominican Republic"
        img="/img1@2x.png"
        propGap="-15px"
      />
      <Link
        border="/border@2x.png"
        turkey="Ecuador"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Egypt"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="El Salvador"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Estonia"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Faroe Islands"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Fiji"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Finland"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="France"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="French Guiana"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Gabon"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Georgia"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Germany"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Ghana"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Gibraltar"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Greece"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Grenada"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Guadeloupe"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Guatemala"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Guernsey"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Guinea"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Guinea-Bissau"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Guyana"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Haiti"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Honduras"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Hong Kong"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Hungary"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Iceland"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="India"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Indonesia"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Iraq"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Ireland"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Isle of Man"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Israel"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Italy"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Jamaica"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Japan"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Jersey"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Jordan"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Kazakhstan"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Kenya"
        img="/img1@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Kuwait"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Kyrgyzstan"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Latvia"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Lesotho"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Liberia"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Liechtenstein"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Lithuania"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Luxembourg"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Macao"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Madagascar"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Malawi"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Malaysia"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Malta"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Martinique"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Mauritius"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Mayotte"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Mexico"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Monaco"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Mongolia"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Montenegro"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Montserrat"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Morocco"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Mozambique"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Nauru"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Netherlands"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="New Zealand"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Nicaragua"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Niger"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Nigeria"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Norway"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Oman"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Pakistan"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Panama"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Papua New Guinea"
        img="/img2@2x.png"
        propGap="-4.18px"
      />
      <Link
        border="/border@2x.png"
        turkey="Paraguay"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Peru"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Philippines"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Poland"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Portugal"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Puerto Rico"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Qatar"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Réunion"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Romania"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Rwanda"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Saint Barthélemy"
        img="/img2@2x.png"
        propGap="14.48px"
      />
      <div className="link2">
        <div className="border-group">
          <img className="border-icon1" alt="" src="/border@2x.png" />
          <div className="saint-martin-french-container">
            <span>
              <p className="saint-martin-french">Saint Martin (French</p>
              <p className="part">part)</p>
            </span>
          </div>
        </div>
        <img className="img-icon4" alt="" src="/img2@2x.png" />
      </div>
      <Link
        border="/border@2x.png"
        turkey="Samoa"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Saudi Arabia"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Serbia"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Seychelles"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Singapore"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Slovakia"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Slovenia"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="South Africa"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="South Korea"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="South Sudan"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Spain"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Sri Lanka"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Sudan"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Suriname"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Sweden"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Switzerland"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Taiwan"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Thailand"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Tunisia"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Turkey"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Uganda"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Ukraine"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="United Arab Emirates"
        img="/img2@2x.png"
        propGap="-25.15px"
      />
      <Link
        border="/border@2x.png"
        turkey="United Kingdom"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="United States"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Uruguay"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Uzbekistan"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Vanuatu"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Vietnam"
        img="/img2@2x.png"
        propGap="20px"
      />
      <Link
        border="/border@2x.png"
        turkey="Zambia"
        img="/img2@2x.png"
        propGap="20px"
      />
    </div>
  );
};

DestinationGrid.propTypes = {
  className: PropTypes.string,
};

export default DestinationGrid;
